apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frost-notifier-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
